### ISSUE TITLE
Please remove LC_API dependence...

### ISSUE THREAD

**Issue by Fundryi** [Venterok/HullBreakerCompany#1]
Hi, as the title says.

Its so annoying currently with the API thing, the mod was working fine without it, and now people have issues connecting even when they have LC_API installed because a lot have different version, or just in general other bugs.

This is just annoying.
I like the mod, but just annoying to see mods that don't need that API add it to dependencies so its "listed in modded server list".

**Comment by Venterok** [comment]
Ok, I'll look into it and release an update soon if everything works well
