### ISSUE TITLE
Add "Base Game Value: x" to each Configs description

### ISSUE THREAD

**Issue by Frewsty** [Venterok/HullBreakerCompany#10]
Difficulty has a config, but for someone with no experience its hard to find out what the base game default value is.

I suggest adding a "Base Game Value" in the configs description that are general (like spawn rate) so that people may set the value to it's original base game value.

The "default" value shows the default value set by the mod, which in my experience, seems to be higher than base game's value.

**Comment by Venterok** [comment]
Added in v1.3.0, release today
