### ISSUE TITLE
[FEAT] Support for outside enemies

### ISSUE THREAD

**Issue by xamionex** [Venterok/HullBreakerCompany#13]
Add support for these:
- [Eyeless Dogs](https://lethal.miraheze.org/wiki/Eyeless_Dog)
- [Forest Keepers](https://lethal.miraheze.org/wiki/Forest_Keeper)
- [Earth Leviathans](https://lethal.miraheze.org/wiki/Earth_Leviathan)
- [Baboon Hawks](https://lethal.miraheze.org/wiki/Baboon_Hawk)

to be used in custom events, would be awesome

**Comment by Venterok** [comment]
Added in v1.3.0, release today
