### ISSUE TITLE
Forest giant is misspelled

### ISSUE THREAD

**Issue by xamionex** [Venterok/HullBreakerCompany#14]
In [Plugin.cs](https://github.com/Venterok/HullBreakerCompany/blob/3a2b4faa66f198578c1a28e3ebc14948570e5504/Plugin.cs#L66) and in [README.md](https://github.com/Venterok/HullBreakerCompany/blob/3a2b4faa66f198578c1a28e3ebc14948570e5504/README.md?plain=1#L82)

Just a small observation ;)

**Comment by Venterok** [comment]
fixed in next patch
