### ISSUE TITLE
Landmine event causes custom map objects to have increased spawnrate

### ISSUE THREAD

**Issue by EvaisaDev** [Venterok/HullBreakerCompany#16]
This line of code
```cs
if ((turretComponent != null && turret) || (landmineComponent != null && landmine) || (turretComponent == null && landmineComponent == null))
{
	unit.numberToSpawn = curve;
}
```
Means that custom objects, which do not have a turret component or a landmine component, get increased spawnrate during landmine events.
This is sub optimal, as it is causing the teleporter traps from my mod to spawn all over the place, when they are supposed to have a max spawn count of 4.
You should remove this part ` || (turretComponent == null && landmineComponent == null)`, not sure why that is even there.

**Comment by Venterok** [comment]
rofl, simple carelessness, I fixed it, I'll release an update in a couple of hours
