### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Fundryi** [Venterok/HullBreakerCompany#2]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HullBreakerCompany.Events.OpenTheNoorEvent.Execute (SelectableLevel level, System.Collections.Generic.Dictionary`2[TKey,TValue] componentRarity) (at <8aa385bc7ab64ad190f1a937f521e7a8>:0)
HullBreakerCompany.Plugin.ModifiedLoad (SelectableLevel& newLevel) (at <8aa385bc7ab64ad190f1a937f521e7a8>:0)
(wrapper dynamic-method) RoundManager.DMD<RoundManager::LoadNewLevel>(RoundManager,int,SelectableLevel)
StartOfRound+<OpenShipDoors>d__230.MoveNext () (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:0)

**Comment by Venterok** [comment]
When the error occurred, did it change something in the game itself? For example, the world might not load “Waiting for Crew”, etc.

**Comment by Fundryi** [comment]
It happens when we started the round, aka "Waiting for Crew" yes, we were stuck in it then, we needed to restart the lobby/game.

**Comment by Venterok** [comment]
This usually happens if the message could not be sent. The standard sending method does not check for an empty message, and if it is still empty, the game will not launch. I checked and hope everything will work. I will post the changes in v1.1.8

**Comment by Venterok** [comment]
I will close the issue, if this happens again, please let me know
