### ISSUE TITLE
[Suggestion] Support for Masked as an enemy type for custom events?

### ISSUE THREAD

**Issue by Clark919** [Venterok/HullBreakerCompany#21]
As the title suggests. Masked doesn't appear in your list so I presume it either doesn't work or we don't know what the identifier for it is, even though it is an enemy that can naturally occur. I've seen the tag `maskedplayer` be thrown about but not sure if this would work.

**Comment by Venterok** [comment]
As far as I understand and look at the code, Masked Player does not spawn, it can only appear if the player is wearing a mask

**Comment by Clark919** [comment]
> As far as I understand and look at the code, Masked Player does not spawn, it can only appear if the player is wearing a mask

This definitely isn't the case in vanilla LC. The masked definitely spawn on at least Rend and Titan naturally albeit rarely, I can confirm that much.

**Comment by Clark919** [comment]
Not the most creditable source, but [this](https://www.reddit.com/r/lethalcompany/comments/18env0v/was_playing_on_titan_foggy_with_a_mate_and_found/?utm_source=share&utm_medium=web2x&context=3) is one of many clips floating around of (presumably) vanilla LC with no one equipping a mask but encountering Masked. Not sure how this is seen in the code but it's certainly possible as a natural occurrence.

**Comment by Venterok** [comment]
Well, if so, then I’ll add it in the next update

**Comment by Clark919** [comment]
> Well, if so, then I’ll add it in the next update

Sounds good. An in-built event to increase their spawn rate could be fun as well if that's a possibility.
