### ISSUE TITLE
Suggestions for Events

### ISSUE THREAD

**Issue by Doctor-Duck** [Venterok/HullBreakerCompany#3]
Would it be possible to add a description for what each event does in the config? When the config just says "FlowerMan" or "Bee", it is a little confusing on what it means. I know in your v1.1.0 changelog you have descriptions for the new events you added, so perhaps doing something like that for each of the existing events in the config would help.

Another suggestion would be to allow for only a certain number of events to spawn per day. So maybe on the first day you'd only have 1 event, but on day 2 you'd have three. You could control this with something that picks a random value for how many events, and have it inherit the max value of events possible that is set in the config. I think adding a true or false option for this setting would be great for those who want the feature either on or off.

**Comment by Venterok** [comment]
I think in the big update v1.2.0 I can do this

**Comment by Venterok** [comment]
v1.2.0 released
