### ISSUE TITLE
Waiting for crew... (1.1.8)

### ISSUE THREAD

**Issue by rogedkone** [Venterok/HullBreakerCompany#4]
try land on moon (new save)
![image](https://github.com/Venterok/HullBreakerCompany/assets/85563010/f0abef2b-9cdc-43e8-8583-30a075d2b26e)

![image](https://github.com/Venterok/HullBreakerCompany/assets/85563010/fe74c557-9099-40be-8d18-4ad5e2c34bdb)

![image](https://github.com/Venterok/HullBreakerCompany/assets/85563010/ce62db7d-a7d7-4b45-9adf-593a99f51b50)

change extension for upload to github
[HullBreakerCompany.txt](https://github.com/Venterok/HullBreakerCompany/files/13474197/HullBreakerCompany.txt)

**Comment by Venterok** [comment]
You can send BepInEx LogOutput.log?

**Comment by Venterok** [comment]
steamapps\common\Lethal Company\BepInEx\LogOutput.log

**Comment by rogedkone** [comment]
unexpectedly, the world was created successfully at first, then after going to the main menu and re-creating, an error again
[LogOutput.log](https://github.com/Venterok/HullBreakerCompany/files/13474529/LogOutput.log) sry for late answer

**Comment by Venterok** [comment]
Сколько бы я мод не тестировал, у меня такой проблемы не бывало, peposad, попробуй включить вот это в BepInex конфиге
![image](https://github.com/Venterok/HullBreakerCompany/assets/67825103/49a403cf-6041-4e93-8ea0-e38fdf767c08)

**Comment by Venterok** [comment]
Если ещё раз не запустится, то более подробно увижу в чём дело

**Comment by rogedkone** [comment]
Из догадок, в конфиге указано 3 евента, в чате пишет два. Какие-то евенты не появляются (хотя должны были).
Возможно мод не видит 0 у каких-то евентов.
Сейчас вместо 3, отобразился 1. (Следите за тем что под ногами)
[LogOutput.log](https://github.com/Venterok/HullBreakerCompany/files/13474632/LogOutput.log)

**Comment by Venterok** [comment]
Нет дело в другом, у меня ивенты идут по очереди через цикл, если из за какого то крашнуло, то он не выведется, я попробую щас с твоим cfg позапускать планеты

**Comment by rogedkone** [comment]
Планета стартовая. Удаляю сейв, запускаю, сразу дёргаю рычаг. Ждать пробовал, дальше waiting ничего

**Comment by Venterok** [comment]
Я так и делаю, постоянно удаляю сейв и перезапускаю, у меня нету такого. Щас буду смотреть в чём дело

**Comment by Venterok** [comment]
18 раз запустил, и всё работает, из модов только hullbreaker
[LogOutput.log](https://github.com/Venterok/HullBreakerCompany/files/13474737/LogOutput.log)

**Comment by rogedkone** [comment]
BepInEx.cfg // можешь проверить с этим параметром? 
![image](https://github.com/Venterok/HullBreakerCompany/assets/85563010/1e1233ac-19b8-4a0d-9d10-8a493e77ee8d)

**Comment by Venterok** [comment]
Видимо это и вызывает ошибку, { = true } и у меня крашит, я добавил try & catch, теперь хотябы игра загружается если не получилось GameObject получить

**Comment by Venterok** [comment]
Выпущу сейчас v1.1.9 с try & catch, а у тебя есть варианты не использовать HideManagerGameObject = true ?

**Comment by rogedkone** [comment]
Это нужно для какого-то другого мода (вроде связанного с камерами) меняет экран с камерой у двери на камеру человека за которым следит терминал.

**Comment by Venterok** [comment]
Я залил на thunderstore v1.1.9, проверь будет ли щас загружать игру

**Comment by rogedkone** [comment]
Заработало даже с кучей всяких разных модов :) очень оперативно!
![image](https://github.com/Venterok/HullBreakerCompany/assets/85563010/0057ee96-021f-403f-ab87-412176c73465)

**Comment by Venterok** [comment]
Если будут проблемы, пиши
