### ISSUE TITLE
Cant spectate when dead (stuck frame)

### ISSUE THREAD

**Issue by Fundryi** [Venterok/HullBreakerCompany#6]
[Info   :HULLBREAKER] Player killed, one for all is active: True
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HullBreakerCompany.Plugin.OneForAll () (at <b6ef93825b524d68946598e37083f34a>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::KillPlayerServerRpc>(GameNetcodeStuff.PlayerControllerB,int,bool,UnityEngine.Vector3,int,int)
GameNetcodeStuff.PlayerControllerB.KillPlayer (UnityEngine.Vector3 bodyVelocity, System.Boolean spawnBody, CauseOfDeath causeOfDeath, System.Int32 deathAnimation) (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)
GameNetcodeStuff.PlayerControllerB.DamagePlayer (System.Int32 damageNumber, System.Boolean hasDamageSFX, System.Boolean callRPC, CauseOfDeath causeOfDeath, System.Int32 deathAnimation, System.Boolean fallDamage, UnityEngine.Vector3 force) (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)
HoarderBugAI.OnCollideWithPlayer (UnityEngine.Collider other) (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)
EnemyAICollisionDetect.OnTriggerStay (UnityEngine.Collider other) (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)

For some reason this error happens when I die, and then I stuck in one frame, I can hear and change spectators, but it won't show me the normal gameplay, just the moment I died.

**Comment by Fundryi** [comment]
oh and this error, the above is most likely not the cause/related to your mod sry.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
HullBreakerCompany.Plugin.OneForAll () (at <b6ef93825b524d68946598e37083f34a>:0)
(wrapper dynamic-method) GameNetcodeStuff.PlayerControllerB.DMD<GameNetcodeStuff.PlayerControllerB::KillPlayerServerRpc>(GameNetcodeStuff.PlayerControllerB,int,bool,UnityEngine.Vector3,int,int)
GameNetcodeStuff.PlayerControllerB.__rpc_handler_1346025125 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <39ddadb2aa5843e586a6c642ee60b0b5>:0)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <1b23ec5fcbfc4fbca0db70afcdb9b715>:0)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
GameNetcodeStuff.PlayerControllerB:DMD<GameNetcodeStuff.PlayerControllerB::KillPlayerServerRpc>(PlayerControllerB, Int32, Boolean, Vector3, Int32, Int32)
GameNetcodeStuff.PlayerControllerB:KillPlayer(Vector3, Boolean, CauseOfDeath, Int32)
GameNetcodeStuff.PlayerControllerB:DamagePlayer(Int32, Boolean, Boolean, CauseOfDeath, Int32, Boolean, Vector3)
HoarderBugAI:OnCollideWithPlayer(Collider)
EnemyAICollisionDetect:OnTriggerStay(Collider)

**Comment by Venterok** [comment]
To understand what's going on, I need logs, the version of the installed mod. with a high degree of probability the issue is not in my hullbreaker, when I tested for 3 hours in a row, I never encountered any error

**Comment by Venterok** [comment]
In the logs I write which events were selected and was not loaded in them; I cannot determine otherwise. In v1.1.9, there is protection against NullReferenceException, so I don't know

**Comment by Fundryi** [comment]
Hi, sorry, it doesn't always happen, but often when you die from a monster that was spawned by HullBreaker I think.

You can test it yourself in that modpack: 
https://thunderstore.io/c/lethal-company/p/Fundryi/SillyCatPack/

**Comment by Venterok** [comment]
the mod works with errors, if a parameter `[Chainloader] HideManagerGameObject = true`, I don’t know what to do with this yet, this is because of CapyCat-Solos_Bodycams

![image](https://github.com/Venterok/HullBreakerCompany/assets/67825103/40d44a8b-e0b6-4351-b183-79dd98d2adf9)
![image](https://github.com/Venterok/HullBreakerCompany/assets/67825103/d8768126-ee0e-40a7-8d93-7ece29eb184c)

**Comment by Fundryi** [comment]
Yea I was guessing it was that option/mod, I disabled it now and remove the BodyCam mod for now, lets see if the dev can fix this in the future.
I don't think you can fix this.

**Comment by Venterok** [comment]
In theory, I can somehow solve this, but I have no experience specifically in mods, sry

**Comment by Venterok** [comment]
https://thunderstore.io/c/lethal-company/p/CapyCat/Solos_Bodycams/


![image](https://github.com/Venterok/HullBreakerCompany/assets/67825103/506b64d0-c943-421f-b0ce-c7962edc5bd7)
