### ISSUE TITLE
Error Startup on 1.2.0 version

### ISSUE THREAD

**Issue by Fundryi** [Venterok/HullBreakerCompany#8]
[Message:   BepInEx] BepInEx 5.4.21.0 - Lethal Company (18.11.2023 11:13:12)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 24 plugins to load
[Warning:   BepInEx] Plugin [AdditionalSuits 1.0.2] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Late Company 1.0.4] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [LetMeLookDown 1.0.1] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [TZP Reworked: Healing 1.1.0.0] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [HDLethalCompany-Sligili 1.5.1] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [Health Station mod 1.0.0.1] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Warning:   BepInEx] Plugin [More Suits 1.3.2] targets a wrong version of BepInEx (5.4.22.0) and might not work until you update
[Info   :   BepInEx] Loading [FPSSpectate 1.0.0]
[Info   :   BepInEx] Loading [VoiceHUD 1.0.4]
[Info   :   BepInEx] Loading [AdditionalSuits 1.0.2]
[Info   :ACS.AdditionalSuits] AdditionalSuits - initializing...
[Info   :ACS.AdditionalSuits] AdditionalSuits - initialized!
[Info   :   BepInEx] Loading [Ship Clock 0.9.0]
[Info   :   BepInEx] Loading [ShipLoot 1.0]
[Info   :   BepInEx] Loading [Bigger Battery 1.0.1]
[Info   :Bigger Battery] Plugin Bigger Battery-1.0.1 loaded!
[Info   :   BepInEx] Loading [LetMeLookDown 1.0.1]
[Info   :LetMeLookDown] LetMeLookDown mod loaded
[Info   :   BepInEx] Loading [SkipToMultiplayerMenu 1.0.0]
[Info   :SkipToMultiplayerMenu] SkipToMultiplayerMenu loaded
[Info   :   BepInEx] Loading [FriendlyFirelessCompany 0.1.0]
[Info   :FriendlyFirelessCompany] Plugin FriendlyFirelessCompany is loaded!
[Info   :   BepInEx] Loading [HDLethalCompany-Sligili 1.5.1]
[Info   :HDLethalCompany-Sligili] HDLethalCompany loaded
[Error  : Unity Log] Unable to open archive file: D:/r2modman/r2modmanPlus-local/LethalCompany/profiles/NPLX/BepInEx/plugins/HDLethalCompany/hdlethalcompany
[Error  : Unity Log] Failed to read data for the AssetBundle 'hdlethalcompany'.
[Info   :   BepInEx] Loading [TZP Reworked: Healing 1.1.0.0]
[Info   :Hotoni.TZPHEAL] TZP HEAL loaded
[Info   :   BepInEx] Loading [HullBreakerCompany 1.2.0]
[Info   :HULLBREAKER 1.2.0] Ready to break hull; HullBreakerCompany
[Error  : Unity Log] DirectoryNotFoundException: Could not find a part of the path 'D:\r2modman\r2modmanPlus-local\LethalCompany\profiles\NPLX\BepInEx\HullEvents'.
Stack trace:
System.IO.Enumeration.FileSystemEnumerator`1[TResult].CreateDirectoryHandle (System.String path, System.Boolean ignoreNotFound) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Enumeration.FileSystemEnumerator`1[TResult]..ctor (System.String directory, System.IO.EnumerationOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Enumeration.FileSystemEnumerable`1+DelegateEnumerator[TResult]..ctor (System.IO.Enumeration.FileSystemEnumerable`1[TResult] enumerable) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Enumeration.FileSystemEnumerable`1[TResult]..ctor (System.String directory, System.IO.Enumeration.FileSystemEnumerable`1+FindTransform[TResult] transform, System.IO.EnumerationOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles (System.String directory, System.String expression, System.IO.EnumerationOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Directory.InternalEnumeratePaths (System.String path, System.String searchPattern, System.IO.SearchTarget searchTarget, System.IO.EnumerationOptions options) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern, System.IO.EnumerationOptions enumerationOptions) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.IO.Directory.GetFiles (System.String path, System.String searchPattern) (at <787acc3c9a4c471ba7d971300105af24>:0)
HullBreakerCompany.Plugin.LoadEventDataFromCfgFiles () (at <12ecb5bbde714538a9a0708b3ca164ec>:0)
HullBreakerCompany.Plugin.Awake () (at <12ecb5bbde714538a9a0708b3ca164ec>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Rendering.HighDefinition.HDRenderPipelineAsset:OnEnable()

[Info   :   BepInEx] Loading [LCBetterSaves 1.4.0]
[Info   :LCBetterSaves] Plugin LCBetterSaves is loaded!
[Info   :   BepInEx] Loading [LethalCompanyDRP 1.2.0]
[Info   :LethalCompanyDRP] Started LethalCompanyDRP
[Info   :   BepInEx] Loading [MikesTweaks 1.8.2]
[Info   :MikesTweaks] Plugin mikes.lethalcompany.mikestweaks is loaded!
[Info   :   BepInEx] Loading [Jump Delay Patch 0.0.0.1]
[Info   :Jump Delay Patch] Plugin JumpDelayPatch is loaded!
[Info   :   BepInEx] Loading [MouseBind 1.0.0]
[Info   :   BepInEx] Loading [Health Station mod 1.0.0.1]
[Info   :Octolar.Healthstation] Octolar HealthStation mod is now active
[Info   :   BepInEx] Loading [ScrollInverter 1.0.0]
[Info   :ScrollInverter] Plugin ScrollInverter is loaded!
[Info   :   BepInEx] Loading [SpectateEnemy 1.0.0]
[Info   :SpectateEnemy] SpectateEnemy loaded!
[Info   :   BepInEx] Loading [LC Always Hear Active Walkies 1.4.1]
[Info   :suskitech.LCAlwaysHearActiveWalkie] \ /
[Info   :suskitech.LCAlwaysHearActiveWalkie] /|\
[Info   :suskitech.LCAlwaysHearActiveWalkie]  |----|
[Info   :suskitech.LCAlwaysHearActiveWalkie]  |[__]| Always Hear Active Walkies
[Info   :suskitech.LCAlwaysHearActiveWalkie]  |.  .| Version 1.4.1 Loaded
[Info   :suskitech.LCAlwaysHearActiveWalkie]  |____|
[Info   :   BepInEx] Loading [Late Company 1.0.4]
[Info   :Late Company] Late Company loaded!
[Info   :   BepInEx] Loading [WeatherMultipliers 0.2.0]
[Info   :WeatherMultipliers] Plugin WeatherMultipliers is loaded!
[Info   :   BepInEx] Loading [More Suits 1.3.2]
[Info   :More Suits] Plugin More Suits is loaded!
[Message:   BepInEx] Chainloader startup complete
[Info   :HULLBREAKER 1.2.0] HullManager created
[Info   :SkipToMultiplayerMenu] Loading GameManager in InitScene.
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0; (0.00, 0.00, 0.00, 0.00) (True)
[Info   : Unity Log] subcribing to steam callbacks
Setting breakpad minidump AppID = 1966720
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198200120293 [API loaded no]
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0; (0.00, 0.00, 0.00, 0.00) (True)
[Info   :LethalCompanyDRP] Discord RPC Started
[Info   :SkipToMultiplayerMenu] Skipping to MainMenu scene.
[Error  : Unity Log] Panel label not found.
[Error  : Unity Log] Delete file game object not found.
[Error  : Unity Log] Error occurred while refreshing save buttons: Object reference not set to an instance of an object
[Error  : Unity Log] Error occurred while updating files panel rect: Failed to find FilesPanel RectTransform.
[Info   : Unity Log] [FacepunchTransport] - Initialized access to Steam Relay Network.
[Info   : Unity Log] [FacepunchTransport] - Fetched user Steam ID.
[Info   : Unity Log] Set version num
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0; (0.00, 0.00, 0.00, 0.00) (True)
[Info   : Unity Log] Back
[Info   : Unity Log] Positioning based on 3 saves.
[Info   : Unity Log] Found file: LCSaveFile0
[Info   : Unity Log] Found file: LCSaveFile1
[Info   : Unity Log] Found file: LCSaveFile2
[Info   : Unity Log] Renamed LCSaveFile0 to TempFile0
[Info   : Unity Log] Renamed LCSaveFile1 to TempFile1
[Info   : Unity Log] Renamed LCSaveFile2 to TempFile2
[Info   : Unity Log] Renamed TempFile0 to LCSaveFile0
[Info   : Unity Log] Renamed TempFile1 to LCSaveFile1
[Info   : Unity Log] Renamed TempFile2 to LCSaveFile2
[Info   : Unity Log] [Dissonance:Core] (11:23:46.283) DissonanceComms: Loading default playback prefab
[Info   : Unity Log] [Dissonance:Core] (11:23:46.294) DissonanceComms: Starting Dissonance Voice Comms (8.0.4)
- Network: [DissonanceSetup (Dissonance.Integrations.Unity_NFGO.NfgoCommsNetwork)]
- Quality Settings: [Quality: Medium, FrameSize: Small, FEC: True, DenoiseAmount: Moderate, RNN: False (0,65) VoiceDuckLevel: 1 VAD: MediumSensitivity]
- Codec: [Codec: Opus, FrameSize: 960, SampleRate: 48kHz]

**Comment by Fundryi** [comment]
FYI: fixed it with creating that folder manually, but I doubt the above should be happening anyways.

**Comment by Venterok** [comment]
ty, fixed in v1.2.1, uploaded in thunderstore, try now
