### ISSUE TITLE
Difficulty ramp up

### ISSUE THREAD

**Issue by Thunderkill** [Venterok/HullBreakerCompany#9]
I am not sure if it's intended, but some values like these:

```csharp
n.maxEnemyPowerCount += 2000;
n.maxOutsideEnemyPowerCount += 20;
n.maxDaytimeEnemyPowerCount += 200;
```

get added to the level's difficulty each time you land on said planet, and it is carried even if you fail a quota and restart the game that way. This makes the game ridiculously difficult on the next run if you fail a game. (or have a long run).

Also the numbers are quite extreme, Titan's default maxEnemyPowerCount is only 18, not sure if 2k is intended

**Comment by Thunderkill** [comment]
This issue still persist on 1.2.5, also the loot value increases for each landing on the same planet. I don't think it's supposed to be that way

Here i have landed 6 times on experimentation
![image](https://github.com/Venterok/HullBreakerCompany/assets/7321298/3950eec8-cd35-4ec2-b879-e8c78e152c80)

**Comment by Venterok** [comment]
AAAAAAAAA, I wrong understood issue, I was sleepy, now I’ll review everything

**Comment by Venterok** [comment]
The previous values were marked //TODO during development, then I accidentally deleted the mark, I should have changed it, but forgot. Now I think this increase will be fair.

![изображение](https://github.com/Venterok/HullBreakerCompany/assets/67825103/7aad9f8d-a1b1-402c-bcdb-54f484fb9567)

**Comment by Venterok** [comment]
Maybe maxEnemyPowerCount += 4/6

**Comment by Venterok** [comment]
I will release these changes in v1.2.6, if there are still problems, I will correct them further

**Comment by Thunderkill** [comment]
Now the power does not ramp up ridiculously hard, but you still missed the point that the values persist even if you fail a game (get fired).

1. Play long run
2. Get fired
3. Next game has the previous game's difficulty applied on all levels you previously landed on. The mod does not reset the values when getting fired

**Comment by Venterok** [comment]
I know, in 1.3.0 I will add a reset and return the old values, it will be better, now I’m taking a short break
